 1.         $$ ::= expression
 2. expression ::= s, expr, s
 3.       expr ::= expr-1
 4.     expr-1 ::= pop-expr
 5.     expr-1 ::= expr-2
 6.   pop-expr ::= POP, s, expr-1
 7.     expr-2 ::= sop-expr
 8.     expr-2 ::= expr-3
 9.   sop-expr ::= expr-3, s, SOP
10.     expr-3 ::= bop-expr
11.     expr-3 ::= expr-4
12.   bop-expr ::= $1_alt, s, BOP, s, $2_alt
13.     expr-4 ::= basic
14.     expr-4 ::= '(', s, expr, s, ')'
15.      basic ::= ['abcde']
16.        BOP ::= 'B', 'O', 'P'
17.        POP ::= 'P', 'O', 'P'
18.        SOP ::= 'S', 'O', 'P'
19.          s ::= $3_starⁿ
20.     $1_alt ::= expr-3
21.     $1_alt ::= sop-expr
22.     $2_alt ::= expr-4
23.     $2_alt ::= pop-expr
24.   $3_starⁿ ::= ε
25.   $3_starⁿ ::= $4_plus
26.    $4_plus ::= [#9; #A; #D; ' ']
27.    $4_plus ::= [#9; #A; #D; ' '], $4_plus
